### ISSUE TITLE
No coverage reports generated

### ISSUE THREAD

**Issue by SquishyMucus** [durad/tscover#4]
I don't seem to have any coverage generated, no coverage folder or any files.

I see that the TS files are transpiled into js and if I use the instrument flag I see the .coverage files generated but no coverage reports. Any suggestions what I could be missing ?

**Comment by durad** [comment]
After running transpiled code you should see the **coverage** subfolder being generated. Html report as well as lcov.info file should be in that folder. Let me know if this works for you.
